# Generated by Django 4.2.5 on 2023-09-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="text",
            name="summery",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="text",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
