# Generated by Django 4.2.5 on 2023-09-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0002_text_summery_alter_text_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="text",
            name="description",
            field=models.JSONField(null=True),
        ),
    ]
